const DATE_DURATION_DECADE = 'Decade';
const DATE_DURATION_YEAR = 'Year';
const DATE_DURATION_MONTH = 'Month';
const DATE_DURATION_WEEK = 'Week';
const DATE_DURATION_DAY = 'Day';

module.exports = {
    DATE_DURATION_DECADE,
    DATE_DURATION_YEAR,
    DATE_DURATION_MONTH,
    DATE_DURATION_WEEK,
    DATE_DURATION_DAY,
};
