const VIEW_TYPE_AREA_CHART = 'area-chart';
const VIEW_TYPE_BAR_CHART = 'bar-chart';
const VIEW_TYPE_BUBBLE_CHART = 'bubble-chart';
const VIEW_TYPE_GALLERY = 'gallery';
const VIEW_TYPE_GLOBE = 'globe';
const VIEW_TYPE_LINE_GRAPH = 'line-graph';
const VIEW_TYPE_MAP = 'map';
const VIEW_TYPE_PIE_CHART = 'pie-chart';
const VIEW_TYPE_PIE_SET = 'pie-set';
const VIEW_TYPE_REGIONAL_MAP = 'regional-map';
const VIEW_TYPE_SCATTERPLOT = 'scatterplot';
const VIEW_TYPE_TABLE = 'table';
const VIEW_TYPE_TIMELINE = 'timeline';
const VIEW_TYPE_GROUPED_GALLERY = 'grouped-gallery';
const VIEW_TYPE_TREEMAP = 'treemap';
const VIEW_TYPE_WORD_CLOUD = 'word-cloud';

const VIEW_TYPES = [
    VIEW_TYPE_AREA_CHART,
    VIEW_TYPE_BAR_CHART,
    VIEW_TYPE_BUBBLE_CHART,
    VIEW_TYPE_GALLERY,
    VIEW_TYPE_GLOBE,
    VIEW_TYPE_LINE_GRAPH,
    VIEW_TYPE_MAP,
    VIEW_TYPE_PIE_CHART,
    VIEW_TYPE_PIE_SET,
    VIEW_TYPE_REGIONAL_MAP,
    VIEW_TYPE_SCATTERPLOT,
    VIEW_TYPE_TABLE,
    VIEW_TYPE_TIMELINE,
    VIEW_TYPE_GROUPED_GALLERY,
    VIEW_TYPE_TREEMAP,
    VIEW_TYPE_WORD_CLOUD,
];

module.exports = {
    VIEW_TYPES,
    VIEW_TYPE_AREA_CHART,
    VIEW_TYPE_BAR_CHART,
    VIEW_TYPE_BUBBLE_CHART,
    VIEW_TYPE_GALLERY,
    VIEW_TYPE_GLOBE,
    VIEW_TYPE_LINE_GRAPH,
    VIEW_TYPE_MAP,
    VIEW_TYPE_PIE_CHART,
    VIEW_TYPE_PIE_SET,
    VIEW_TYPE_REGIONAL_MAP,
    VIEW_TYPE_SCATTERPLOT,
    VIEW_TYPE_TABLE,
    VIEW_TYPE_TIMELINE,
    VIEW_TYPE_GROUPED_GALLERY,
    VIEW_TYPE_TREEMAP,
    VIEW_TYPE_WORD_CLOUD,
};
